language: r
cache: packages

r_packages:
  - geojsonlint

r_github_packages:
  - jimhester/covr

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel

before_install:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get update
  - sudo apt-get install libjq-dev

addons:
  apt:
    packages:
      - libv8-dev
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler
      - valgrind

after_success:
  - Rscript -e 'covr::codecov()'

r_check_args: "--as-cran --run-dontrun"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: I7evcyFpHziA83/sYF1rK4u5GgcwxuLinNA50VmEgWpyOJNQnUOqp+oBjLMhOXy5Y3vdgNnqQ6ep3XA1rMWGzPd1LKdwiH4CpWRJAlsw1z5C5F/rLoYo5TeF+ZtmtG6AkvobdKgHJZgplNQaSfBXWC12BdK/gVraGkUSQXtKgMknXQbiS70QMtK0GczQ/EBYuIK506qeYGTydn20wLxQDZtKpJqXDmdl+BA2r3T51lYzDaE1I8hTimZYml3Q4hSk2QND6cmlkgGT03ptkYh/tdOE2mJmkypdIQnxAmv1fttbDRutDLsaXTtmmGEUI9v/IBnkwRvkX1SbfB7wEDCn60MtoNfpzDR0wbzXvBCKvDxTCmfL9B6k0wQjuPwIV6yuxUHFrPwvNO6O3EAd9MnfXp3vy/x0BVoidw5mZjBHgCKAuX7Hstb9cg4M8IIiwlzT9awEOPSV+ZsjWGarUmKlQmE9u91RqrkCoSL57RlwOqOECqkQxbEYx5CBS3onzsfbUd4xnxinEwvv1xB8tpjKlHUJAveOelvx0HBhxU+2VvmkmAXkehQS41b2Zi2FyBT5d33nzrRZh2Zb8W2GNXw2K3dGNkbUw6MXSFVuB3V59ZQgzgqkqxUHMSemh/+tcwqDP9h1Evv18jQHtODiozmzSk3SnDpj3BQ0poGLTyLQquY=
